# Generated by Django 2.2.5 on 2019-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos/')),
            ],
        ),
    ]
