# Generated by Django 2.2.5 on 2019-10-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0004_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/profile_picture/'),
        ),
    ]
