# Generated by Django 2.2.5 on 2019-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0005_announcement_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='profile_picture',
            field=models.ImageField(blank=True, default='photos/profile_picture/default_profile_picture.png', null=True, upload_to='photos/profile_picture/'),
        ),
    ]
