# Generated by Django 2.2.5 on 2019-10-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0008_auto_20191008_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='surname',
        ),
    ]
