# Generated by Django 2.2.5 on 2019-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0009_auto_20191008_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='email',
            field=models.EmailField(default='email@sample.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='surname',
            field=models.CharField(default='surname', max_length=100),
            preserve_default=False,
        ),
    ]
