# Generated by Django 2.2.5 on 2019-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0010_auto_20191009_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='current_job',
            new_name='last_role',
        ),
        migrations.AddField(
            model_name='actor',
            name='last_movie',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
