# Generated by Django 2.2.5 on 2019-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0013_auto_20191017_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='categories',
            field=models.ManyToManyField(blank=True, to='praca_inzynierska.Category'),
        ),
    ]
