# Generated by Django 2.2.5 on 2019-10-25 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('praca_inzynierska', '0014_auto_20191017_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pay_monthly', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120000), django.core.validators.MinValueValidator(1)])),
                ('place', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(blank=True, to='praca_inzynierska.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='praca_inzynierska.Company')),
            ],
        ),
    ]
