# Generated by Django 2.2.5 on 2019-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0015_company_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='place',
            new_name='localization',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='photos/logos/default_logo.jpg', null=True, upload_to='photos/logos/'),
        ),
    ]
