# Generated by Django 2.2.5 on 2019-10-25 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0016_auto_20191025_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.ImageField(blank=True, default='photos/logos/defaul_logo.jpg', null=True, upload_to='photos/job_pictures/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_monthly',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(120000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
