# Generated by Django 2.2.5 on 2019-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0017_auto_20191025_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='visible',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
