# Generated by Django 2.2.5 on 2019-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0018_auto_20191115_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='visible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
            preserve_default=False,
        ),
    ]
