# Generated by Django 2.2.5 on 2019-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0019_auto_20191115_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
