# Generated by Django 2.2.5 on 2019-11-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0020_actor_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
