# Generated by Django 2.2.5 on 2019-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0021_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='photos/profile_picture/default_profile_picture.png', null=True, upload_to='photos/'),
        ),
    ]
