# Generated by Django 2.2.5 on 2020-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca_inzynierska', '0022_auto_20191123_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
